from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from tradingagents.dataflows.calculate_indicators import (
    get_dex_indicators,
    get_builtin_quant_signals,
)
from tradingagents.dataflows.geckoterminal_price import get_dex_ohlcv


def create_quant_signal_analyst(llm):
    def quant_signal_analyst_node(state):
        current_date = state["trade_date"]
        ticker = state["company_of_interest"]

        tools = [
            get_dex_ohlcv,
            get_dex_indicators,
            get_builtin_quant_signals,
        ]

        system_message = (
            "You are a quantitative strategy signal analyst focused on crypto hourly trading (next 6-24 hours)."
            " Your task is to receive built-in quant strategy signals generated by fixed formulas, then analyze and interpret them with clear execution implications."
            "\n\n"
            "Tool discipline:"
            "\n1) Always call get_dex_ohlcv first to fetch and cache latest candles."
            "\n2) Then call get_builtin_quant_signals to obtain built-in factor signals."
            "\n3) You may call get_dex_indicators only as supplemental context if needed."
            "\n\n"
            "Built-in factor formulas (must explicitly reference all of them in analysis):"
            "\n- alpha101_12 = sign(delta(volume,1)) * (-delta(close,1))"
            "\n- alpha101_2_variant = -corr(delta(log(volume),2), (close-open)/open, 6)"
            "\n- gtja_191_variant = ((EMA(close,12)-close[t-12])/StdDev(close,12)) * (volume/SMA(volume,12))"
            "\n\n"
            "Output requirements:"
            "\n1) One-paragraph executive summary for next 6-24h."
            "\n2) For each built-in factor, provide: current signal (LONG/SHORT/NEUTRAL), strength (0-1), what it implies for next 6-24h, and invalidation conditions."
            "\n3) Resolve cross-factor conflicts and provide a blended quant view (LONG/SHORT/NEUTRAL)."
            "\n4) End with a Markdown table columns: factor_name, current_signal, strength_0_to_1, formula_brief, interpretation, invalidation, next_6_24h_implication."
            "\nAvoid vague language; make the report concrete and executable."
        )

        prompt = ChatPromptTemplate.from_messages(
            [
                (
                    "system",
                    "You are a helpful AI assistant, collaborating with other assistants."
                    " Use the provided tools to progress towards answering the question."
                    " If you are unable to fully answer, that's OK; another assistant with different tools"
                    " will help where you left off. Execute what you can to make progress."
                    " If you or any other assistant has the FINAL TRANSACTION PROPOSAL: **BUY/HOLD/SELL** or deliverable,"
                    " prefix your response with FINAL TRANSACTION PROPOSAL: **BUY/HOLD/SELL** so the team knows to stop."
                    " You have access to the following tools: {tool_names}.\n{system_message}"
                    "For your reference, the current date is {current_date}. The crypto pair/token we want to analyze is {ticker}",
                ),
                MessagesPlaceholder(variable_name="messages"),
            ]
        )

        prompt = prompt.partial(system_message=system_message)
        prompt = prompt.partial(tool_names=", ".join([tool.name for tool in tools]))
        prompt = prompt.partial(current_date=current_date)
        prompt = prompt.partial(ticker=ticker)

        chain = prompt | llm.bind_tools(tools)
        result = chain.invoke(state["messages"])

        report = ""
        if len(result.tool_calls) == 0:
            report = result.content

        return {
            "messages": [result],
            "quant_strategy_report": report,
        }

    return quant_signal_analyst_node